name: reactive_mvvm
description: Reactive MVVM Library that facilitates complex state scenarios especially form entry styled after bloc using RxDart.
version: 1.0.15
homepage: https://github.com/Concerti-IO/reactive-mvvm
repository: https://github.com/Concerti-IO/reactive-mvvm

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.27.2

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
